import Header from "@/app/_components/Header/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../assets/style/tailwind/index.css"
import "../assets/style/scss/index.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kor">
      <body className={inter.className}>
        <Header/>
        <div className={'container mt-[50px] xs:mt-[70px]'}></div>
        {children}
      </body>
    </html>
  );
}
