import Banner from "@/app/_components/Banner/Banner";
import TabArea from "@/app/_components/TabArea/TabArea";
import Footer from "@/app/_components/Footer/Footer";
import Header from "@/app/_components/Header/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../assets/style/tailwind/index.css"
import "../assets/style/scss/index.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kor">
      <body className={inter.className}>
        <Header/>
        <Banner />
        <TabArea/>
        <div className={'container'}>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
